name: Exemplo Artifact
run-name: Exemplo workflow para artifact
on: 
  workflow_dispatch:

env:
  nome-artefato: test-artefato
  
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Listagem de arquivos
        run: ls
      - name: Gerar alguns arquivos
        run: |
          mkdir artefator
          echo "Arquivo de test 01" > ./artefatos/primeiro_arquivo.txt
          echo "Arquivo de test 02" > ./artefatos/segundo_arquivo.txt
          echo "Arquivo de test 03" > ./artefatos/terceiro_arquivo.txt
          echo "Arquivo de test 04" > ./artefatos/quarto_arquivo.txt

      - name: Envio dos arquivos
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with: 
          name: ${{ env.nome-artefato }}
          path: ./artefator
    
      - name: Listagem de arquivos
        run: ls

      - name: Endereço para obter os artefator
        run: |
          echo "${{ steps.upload-artifact.outputs.artifact-url }}"

  download-artifact:
    runs-on: ubuntu-latest
    needs: [upload-artifact]
    steps:
      - name: Listagem de arquivos
        run: ls

      - name: Download Artifact
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.nome-artefato }}

      - name: Listagem de arquivos
        run: ls
      
      
